version: '3.4'
services:
  weaviate:
    container_name: weaviate
    volumes:
      - ${HOST_PERSIST_DIR}:/var/lib/weaviate
    command:
    - --host
    - 0.0.0.0
    - --port
    - '5432'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.20.0
    ports:
      - 5432:5432
    restart: on-failure:0
    environment:
      PORT: 5432
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'none'
      CLUSTER_HOSTNAME: 'node1'

  retrieval_plugin:
    image: stewedharry/retrieval-plugin:1.0
    environment:
      DATASTORE: 'weaviate'
      WEAVIATE_URL: 'http://weaviate:5432'
      WEAVIATE_CLASS: 'OpenAIDocument'
      WEAVIATE_BATCH_SIZE: 20
      WEAVIATE_BATCH_TIMEOUT_RETRIES: 3
      WEAVIATE_BATCH_NUM_WORKERS: 1
      BEARER_TOKEN: ${RETRIEVAL_API_BEARER}
      OPENAI_API_KEY: ${OPENAI_KEY}
      PORT: 5000
      AUTHENTICATION_APIKEY_ENABLED: 'false'
    ports:
    - 5000:5000
    depends_on: 
      - weaviate


